#!/usr/bin/env bash
#### MainsailOS Build Chain
####
#### Klipper Install Module
####
#### Written by Stephan Wendel aka KwadFan <me@stephanwe.de>
#### Copyright 2021 - 2022
#### https://github.com/mainsail-crew/MainsailOS
####
#### This File is distributed under GPLv3
####

# shellcheck enable=require-variable-braces

## Source error handling, leave this in place
set -Eex

# Set LC_ALL to prevent errors
export LC_ALL=C

# Set DEBIAN_FRONTEND to noninteractive
if [[ "${DEBIAN_FRONTEND}" != "noninteractive" ]]; then
    export DEBIAN_FRONTEND=noninteractive
fi

# Source CustomPIOS common.sh
# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

echo_green "Install Input Shaper requirements ..."

### install all deps at once for time consumption reasons.
## APT: Update Repo Database and install Dependencies
# Force apt update
apt update
echo_green "Installing Input Shaper Dependencies ..."
# shellcheck disable=SC2086
# Disabling shellcheck SC2086, because we want "wordsplitting"
check_install_pkgs ${IS_REQ_PREINSTALL_DEPS}

### Check for Klipper Venv installed.
pushd "/home/${BASE_USER}" &> /dev/null || exit 1
if [[ -d "${IS_REQ_PREINSTALL_VENV_DIR}" ]] && [[ -x "${IS_REQ_PREINSTALL_VENV_DIR}/bin/pip" ]]; then
    if [[ -n "${IS_REQ_PREINSTALL_PIP//[[:space:]]/}" ]]; then
        echo_green "Installing configured Python requirements..."
        read -r -a pip_requirements <<< "${IS_REQ_PREINSTALL_PIP}"
        sudo -u "${BASE_USER}" "${IS_REQ_PREINSTALL_VENV_DIR}"/bin/pip install -v "${pip_requirements[@]}"
    else
        # The Trixie configuration installs numpy/matplotlib through APT.
        # Make those distro packages visible inside Klipper's existing venv.
        echo_green "Using system Python packages for Input Shaper..."
        venv_config="${IS_REQ_PREINSTALL_VENV_DIR}/pyvenv.cfg"
        test -f "${venv_config}"
        if grep -q '^include-system-site-packages[[:space:]]*=' "${venv_config}"; then
            sed -i 's/^include-system-site-packages[[:space:]]*=.*/include-system-site-packages = true/' "${venv_config}"
        else
            printf '%s\\n' 'include-system-site-packages = true' >> "${venv_config}"
        fi
    fi
    sudo -u "${BASE_USER}" "${IS_REQ_PREINSTALL_VENV_DIR}/bin/python" -c 'import numpy; import matplotlib'
else
    echo_red "Klipper Venv not found!"
    exit 1
fi

## Cleanup
echo_green "Cleanup ..."
sudo -u "${BASE_USER}" rm -rf "/home/${BASE_USER}/.cache"
popd  &> /dev/null || exit 1

echo_green "Install Input Shaper requirements ... done!"
