name: Deploy to GitHub Pages

on:
  push:
    branches: [v2.1.x]
    paths: [site/**]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: pnpm/action-setup@v6.1.0
        with:
          version: 9.14.2
      - uses: actions/setup-node@v7.0.0
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: site/pnpm-lock.yaml

      - name: Build website
        working-directory: site
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs
          user_name: Mikkel Schmidt
          user_email: mikkel.schmidt@gmail.com
